### ISSUE TITLE
Module is not idempotent

### ISSUE THREAD

**Issue by jhogendorn** [fiunchinho/ansible-aws-elasticsearch-module#12]
If you run this module twice, it will put the cluster into a processing state, even if there are no changes. Since the processing state takes 10-20 minutes to finish, this is a big time sink.

There should probably be a request to describe the elasticsearch domain and only perform updates if there are differences in configuration?

**Comment by jhogendorn** [comment]
So I had a dig into this one, and yes, sorry the module is checking for changes before requesting aws changes. My policy, while valid, when returned from aws is very subtly different (principal was wrapped in an array, delivered back unwrapped). This caused the module to trigger a change request each time.

Probably worth noting as a potential pitfall in the documentation, and to debug by comparing `cluster_policies.json` against the output from something like `aws es describe-elasticsearch-domain --domain-name <mydomain> | jq ".DomainStatus.AccessPolicies | fromjson"`

**Comment by fiunchinho** [comment]
Could you send a PR with that? I could try adding it, but it'll need to wait until next week
